### ISSUE TITLE
[user-feedback] Maybe avoid foreign words in examples

### ISSUE THREAD

**Issue by onlineSem** [trosel/learn-shavian#2]
Hello,

> The letter for ado is 𐑩. This is the letter for "a" as in "a dog". It sort of looks like a guy bowing to the letter next to it, saying "I bid you **adieu!"**
~ Lesson 3

The word "adieu" is read differently from where you're from, and a french speaker may be very confused by your example. 
"Adieu" is pronounced in french with an IPA "æ" sound instead of the english IPA "ə" which I think is the one you're talking about here. 

Great work, otherwise!

**Comment by trosel** [comment]
The new letter name for that is “ago” :)

Thank you for the feedback though! I wasn’t thinking about a non-native reading these lessons
